---
- hosts: localhost
  vars:
    test_prefix: ansible-integration-test
  tasks:
    - name: list projects
      equinix.metal.project_info:
      register: test_projects

    - set_fact:
        matching_projects: "{{ test_projects.projects | selectattr('name', 'match', '^'+test_prefix) | list }}"

    - name: list devices
      equinix.metal.device_info:
        project_id: "{{ item.id }}"
      register: test_devices
      loop: "{{ matching_projects }}"

    - set_fact:
        mp: "{{ test_devices.results | map(attribute='item.id') | list }}"
        md: "{{ test_devices.results | map(attribute='devices') | map('selectattr', 'hostname', 'match', '^'+test_prefix) | map('map', attribute='id') | list }}"

    - set_fact:
        matching_proj_device_ids: "{{ dict(mp | zip(md)) | dict2items(key_name='project_id', value_name='device_ids') | selectattr('device_ids') | list }}"

    - name: delete test devices
      equinix.metal.device:
        device_ids: "{{ item.device_ids }}"
        project_id: "{{ item.project_id }}"
        state: absent
      loop: "{{ matching_proj_device_ids }}"
      ignore_errors: true

    - name: delete test projects
      equinix.metal.project:
        id: "{{ item.id }}"
        state: absent
      loop: "{{ matching_projects }}"
      ignore_errors: true
