plugins:
  become: {}
  cache: {}
  callback: {}
  cliconf: {}
  connection: {}
  httpapi: {}
  inventory:
    device:
      description: Equinix Metal Device inventory source
      name: device
      version_added: 1.0.0
  lookup: {}
  module: {}
  netconf: {}
  shell: {}
  strategy: {}
  vars: {}
version: 1.0.0
