plugins:
  become: {}
  cache: {}
  callback: {}
  cliconf: {}
  connection: {}
  httpapi: {}
  inventory:
    device:
      description: Equinix Metal Device inventory source
      name: device
      version_added: 1.0.0
  lookup: {}
  module:
    device:
      description: Manage a bare metal server in Equinix Metal
      name: device
      namespace: ''
      version_added: 1.1.0
    device_info:
      description: Gather information about Equinix Metal devices
      name: device_info
      namespace: ''
      version_added: 1.2.0
    project:
      description: Create/delete a project in Equinix Metal
      name: project
      namespace: ''
      version_added: 1.2.0
    project_info:
      description: Gather information about Equinix Metal projects
      name: project_info
      namespace: ''
      version_added: 1.2.0
    sshkey:
      description: Create/delete an SSH key in Equinix Metal
      name: sshkey
      namespace: ''
      version_added: 1.3.0
    sshkey_info:
      description: Gather information about Equinix Metal SSH keys
      name: sshkey_info
      namespace: ''
      version_added: 1.3.0
  netconf: {}
  shell: {}
  strategy: {}
  vars: {}
version: 1.3.0
