plugins:
  become: {}
  cache: {}
  callback: {}
  cliconf: {}
  connection: {}
  httpapi: {}
  inventory:
    device:
      description: Equinix Metal Device inventory source
      name: device
      version_added: 1.0.0
  lookup: {}
  module:
    capacity_info:
      description: Gather information about Equinix Metal capacity
      name: capacity_info
      namespace: ''
      version_added: 1.4.0
    device:
      description: Manage a bare metal server in Equinix Metal
      name: device
      namespace: ''
      version_added: 1.1.0
    device_info:
      description: Gather information about Equinix Metal devices
      name: device_info
      namespace: ''
      version_added: 1.2.0
    facility_info:
      description: Gather information about Equinix Metal facilities
      name: facility_info
      namespace: ''
      version_added: 1.4.0
    ip_info:
      description: Gather information about project IP Addresses
      name: ip_info
      namespace: ''
      version_added: 1.4.0
    ip_subnet:
      description: Assign IP subnet to a bare metal server.
      name: ip_subnet
      namespace: ''
      version_added: 1.4.0
    operating_system_info:
      description: Gather information about Equinix Metal operating_systems
      name: operating_system_info
      namespace: ''
      version_added: 1.4.0
    org_info:
      description: Gather information about Equinix Metal organizations
      name: org_info
      namespace: ''
      version_added: 1.4.0
    plan_info:
      description: Gather information about Equinix Metal plans
      name: plan_info
      namespace: ''
      version_added: 1.4.0
    project:
      description: Create/delete a project in Equinix Metal
      name: project
      namespace: ''
      version_added: 1.2.0
    project_info:
      description: Gather information about Equinix Metal projects
      name: project_info
      namespace: ''
      version_added: 1.2.0
    sshkey:
      description: Create/delete an SSH key in Equinix Metal
      name: sshkey
      namespace: ''
      version_added: 1.3.0
    sshkey_info:
      description: Gather information about Equinix Metal SSH keys
      name: sshkey_info
      namespace: ''
      version_added: 1.3.0
    user_info:
      description: Gather information about the logged in user
      name: user_info
      namespace: ''
      version_added: 1.4.0
  netconf: {}
  shell: {}
  strategy: {}
  vars: {}
version: 1.4.1
